### ISSUE TITLE
Enhancement: Add labels to sveltos-agents

### ISSUE THREAD

**Issue by EricaJ6** [projectsveltos/sveltos-agent#226]
Apply labels at the creation time for sveltos-agents. It may reuse the labels from classifier labels to sveltos-agent labels.

**Comment by gianlucam76** [comment]
Solved: https://github.com/projectsveltos/classifier/pull/263

**Comment by gianlucam76** [comment]
documentation: https://projectsveltos.github.io/sveltos/features/configuration_drift/#customize-drift-detection-manager-configuration
